### PR TITLE
Correct reference to literal 'key' string instead of the variable name.

### PR DESCRIPTION
**Pull request by adambossy**
I don't know how this made it to production without breaking unit tests. I am marking this as "proposal" because I need to understand the implications of this and why it's not surfacing on production, as well as to write the corresponding unit tests. 

I also can't find the corresponding PR that merges these changes into `master`. It might just have been a long day, but there is definitely something strange going on.

### CODE REVIEW

**Comment by LiraNuna** [comment]
This is a typo... As far as I know, this function is unused as well.

**Comment by LiraNuna** [comment]
I'm also not sure why tests fail.

**Comment by LiraNuna** [comment]
@adambossy I have reverted the offending commit. I did not intend to commit it (note how it's a direct commit instead of a PR).

**Comment by adambossy** [comment]
@LiraNuna Oh, that makes sense. Thanks for the clarification and speedy fix! 

I think you're right that these functions are unused, however, I made a very small local change that caused these to get used. I'm not sure what downstream effects my code is triggering, but I'll try to investigate and clean up at some point.

**Pull request closed without merging**
