### PR TITLE
Router

### PR DESCRIPTION
**Pull request by 21echoes**
@alts @zsennenga @LiraNuna 

isn't it a great world where this is all you need to do all the right things for a resource?

``` python
class PostRouter(FlaskJSONAPIRouter):
    RESOURCE = PostResource

    def create_model(self, table_data, request=None, session=None):
        # PostResource.MASK.can_create(session.current_user_id) has already been checked
        # table_data has already gone thru PostResource.PARSER.validated_table_data
        # superclass handles wrapping this model in PostResource.SERIALIZER and crafting it into a valid flask response
        return posts_dbm.create_from_json(table_data)

    def update_model(self, table_data, request=None, session=None):
        # PostResource.MASK.can_update(table_data['id'], session.current_user_id) has already been checked
        # table_data has already gone thru PostResource.PARSER.validated_table_data
        # superclass handles wrapping this model in PostResource.SERIALIZER and crafting it into a valid flask response
        return posts_dbm.update_from_json(table_data)

    def delete_model(self, model_id, request=None, session=None):
        # PostResource.MASK.can_delete(model_id, session.current_user_id) has already been checked
        # superclass handles returning the right JSON:API-compliant flask response        
        return posts_dbm.delete_by_id(model_id)

    def list_models(self, request=None, session=None):
        # PostResource.MASK.can_list(session.current_user_id) has already been checked
        # superclass handles wrapping this model in PostResource.SERIALIZER and crafting it into a valid flask response
        # this method would be responsible for checking request.get_sort(), request.get_pagination(), and request.get_filters() and modifying the posts_dbm.all() call appropriately
        return posts_dbm.all()
```

Still definitely needed:
- [ ] discussion
- [ ] handling CRUD for `resource/<string:model_id>/<string:relationship_name>` routes
- [ ] polishing off TODOs
  - [ ] _actually_ calling masks (the example app doesn't have sessions yet, so masks don't make much sense)
  - [ ] ability to register arbitrary routes
  - [ ] ??

### CODE REVIEW

**Comment by LiraNuna** [comment]
This is definitely the direction I'm heading into but I believe this is not the right time for this.

We need these before this can be even be thought about:
- [ ] Automatic generation of Parsers
- [ ] Automatic generation of Serializers
- [ ] Handling of generic fetches:
  - [ ] Sorting
  - [ ] Paging
  - [ ] Filtering

And there are most likely a lot more that I forgot. My end goal is to have a schema-driven framework but there's a lot more work that needs to be done before this happens.

**Comment by 21echoes** [comment]
i think auto-generation should come *far* after this router, but perhaps I'm misunderstanding what you mean by "auto-generation". What's the input, and what's the output?

**Comment by 21echoes** [comment]
I also don't think we can even begin to touch sorting, paging, or filtering without imposing our vision of a model layer on the user of this library, which is beyond this library's scope. We give them ```
def list_models(self, inbound_request=None, inbound_session=None):
        return posts_dbm.all
```
and an interface on that request which makes it easy to pull pagination, sorting, and filtering arguments off of it (`request.get_sort()`, `request.get_pagination()`, and `request.get_filters()`). How those results translate into arguments to their model layer is not this library's concern (are they using mongo? postgres? an external API? we don't know and we can't begin to care without blowing out the scope of this lib dramatically)

**Comment by 21echoes** [comment]
liran and i spoke offline a bit about preferring decorators sooner rather than later, so that the advances in the router superclass are more broadly usable without necessarily jumping all the way in (esp. in our own codebase). I'm not 100% sure that should block this changeset, though. 

Anyway, @LiraNuna 's written a decorator that has similar work to this our own codebase, so I'd probably like us to pair up a bit to decompose that decorator into many smaller decorators, and pull those decorators into this repo properly.

**Comment by zsennenga** [comment]
Router 4 lyfe

**Pull request closed without merging**
